//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavke
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stavke()
        {
            this.Unosis = new HashSet<Unosi>();
        }
    
        public long ItemID { get; set; }
        public string Stavka { get; set; }
        public string Opis { get; set; }
        public string Inventurni_kod { get; set; }
        public Nullable<double> Ulaz { get; set; }
        public Nullable<double> Izlaz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unosi> Unosis { get; set; }
    }
}
